### ISSUE TITLE
Read A Recommendation

### ISSUE THREAD

**Issue by WYB929** [CSCI-GA-2820-FA23-001/recommendations#2]
**As a** customer
**I need** to have a recommendation list for the product I currently view or interested in
**So that** I could have better options to select the product which fit my requirements
   
 ### Details and Assumptions
 * The recommendation list should have several categories like up-sells, cross-sells, accessory, better pricing, etc
 * We could let customer to decide which type of recommendation they want or display all the categories. 
 * For products in the recommendation, it might be good to have the link to redirect customer to the detail page of it. 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I am exploring to find a product I need
 When I see an appropriate product and want to see more options similar or related to this product
 Then I click on recommendation and see the recommendations based on this product with different categories. 
```

**Comment by KimHe-RGB** [comment]
The customer should have a preference "what not to recommend". This preference should be recorded (and stored as cookies).
When the customer explores a product (click into the detailed info page), we fetch recommendation based solely on the product, then filter by their user preference. 

> "We could let customer to decide which type of recommendation they want or display all the categories."

I feel like this is not implemented in other online shopping apps? I am not sure under what conditions users want to block recommendations from certain categories. They may want to block all recommendations, but if they only want to block from some categories (like up-sells or cross-sells), I think this can be filtered by the front-end?

PS. Personalized recommendation that based on user visit history can be a function to implement in the future.
