### ISSUE TITLE
Add paging for Listing all recommendations

### ISSUE THREAD

**Issue by KimHe-RGB** [CSCI-GA-2820-FA23-001/recommendations#28]
## 
As a user making API request at frontend
I need to list recommendations base on a paging size, providing a (optional) `page-index` and `page-size` query string
So that the request does not take too much response time and main memory

## Details
* if `page` is not given, return page 1 by default
* if `page` is given, return the recommendations from index `min(total_pages, page*page_size)` to `min(total_pages, (page+1)*page_size-1)`
* default `page_size` = 10

## Acceptance criteria
Given a user want to get all recommendations and did not specify an `page` query
When the number of recommendations exceeds page size limit
Then return the recommendations on default page

**Comment by sidoodler** [comment]
I think the acceptance criteria should also have the case where a specific page number is given in the query. In that case, what should happen:
1. If there are that many pages of recommendations.
2. If there aren't that many pages of recommendations.
