### ISSUE TITLE
Setup the Server

### ISSUE THREAD

**Issue by WYB929** [CSCI-GA-2820-FA23-001/recommendations#8]
**As a** recommendation developer
**I need** to setup a server
**So that** we could use server to connect frontend part(like webpage to display recommendations )and backend part(like database which saves recommendations). 
   
 ### Details and Assumptions
 * The server should handle the request to from the customer about recommendations. 
 * The server should be able to edit and access recommendations saved in database. 
 * The server could be implemented by Flask. 
 * The server should support serialization and deserialization.
 * The server should use Factory Boy to automate object generation
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the customer send a request about recommendations of a product
 When the server receive the request from the frontend webpage
 Then it could retrieve recommendations of that product from the database and send it back to the frontend webpage. 
```

**Comment by oyster14** [comment]
Add details about serialization, deserialization, and Factory Boy
